In [2]:
import os
from dotenv import load_dotenv

load_dotenv()
print(os.getenv("MONGODB_URI"))

mongodb+srv://<db_username>:VlXHfDRb9zrtbg8N@cluster0.03malbp.mongodb.net/?appName=Cluster0

In [4]:
import pandas as pd
import pymongo

df = pd.read_csv("data/enron_spam_data.csv")
df.head()

,Message ID,Subject,Message,Spam/Ham,Date
0,0,christmas tree farm pictures,NaN,ham,1999-12-10
1,1,"vastar resources , inc .","gary , production from the high island larger ...",ham,1999-12-13
2,2,calpine daily gas nomination,- calpine daily gas nomination 1 . doc,ham,1999-12-14
3,3,re : issue,fyi - see note below - already done .\nstella\...,ham,1999-12-14
4,4,meter 7268 nov allocation,fyi .\n- - - - - - - - - - - - - - - - - - - -...,ham,1999-12-14

In [5]:
data = df.to_dict(orient="records")

In [6]:
import dotenv
import os
dotenv.load_dotenv()

client = pymongo.MongoClient(os.getenv("MONGODB_URL"))
data_base = client[os.getenv("DATA_BASE_NAME")]
collection = data_base[os.getenv("COLLECTION_NAME")]

In [7]:
# Uploading data to MongoDB
rec = collection.insert_many(data)

In [8]:
# Load back data from mongodb
df = pd.DataFrame(list(collection.find()))
df.head(2)

,_id,Message ID,Subject,Message,Spam/Ham,Date
0,6a65a1a47f267d63e5a6e7c1,0,christmas tree farm pictures,NaN,ham,1999-12-10
1,6a65a1a47f267d63e5a6e7c2,1,"vastar resources , inc .","gary , production from the high island larger ...",ham,1999-12-13